# Generated by Django 3.2.1 on 2024-04-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creatred',
            new_name='created',
        ),
    ]
